apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: svadrut/third_kubernetes_app-users:latest
          env:
            - name: AUTH_ADDRESS
              value: localhost
        - name: auth
          image: svadrut/third_kubernetes_app-auth:latest